### ISSUE TITLE
reconsider FINDflare thresholds

### ISSUE THREAD

**Issue by jradavenport** [jradavenport/appaloosa#9]
Currently [we're using](https://github.com/jradavenport/appaloosa/blob/master/appaloosa/appaloosa.py#L384) a set of thresholds from Chen+2015 that seem reasonable.

@ekaterinailin, do you think we should simply the thresholds for flare detection? Can we think of a principled way to decide this?

**Comment by jradavenport** [comment]
My intuition is these thresholds are not terrible. @ekaterinailin I'm going to close this, but please reopen if you disagree!

**Comment by ekaterinailin** [comment]
I mostly use `N2=4` (which overrides `N1=3`), i.e., a more restrictive threshold. This seemed to work well with long cadence data, because this kept the number of initial candidate detections at bay but I still rejected some later based on injection/recovery results. I'd expect going back to ` N2=1` to increase the number of low-confidence candidates.
This could well be different with short cadence data...
